"""empty message

Revision ID: 21b9354833dd
Revises: dcfadb8dcac2
Create Date: 2021-06-25 03:18:58.090263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b9354833dd'
down_revision = 'dcfadb8dcac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_appointee', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'users', ['user_appointee'], ['user_id'])
    op.drop_constraint('users_appointments_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'appointments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('appointments', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_appointments_fkey', 'users', 'appointments', ['appointments'], ['appointment_id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'user_appointee')
    # ### end Alembic commands ###
