"""initial migration

Revision ID: 3ff6d64b32ff
Revises: 
Create Date: 2021-06-23 18:48:48.579290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff6d64b32ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('appointment_title', sa.String(length=100), nullable=True),
    sa.Column('appointment_content', sa.String(length=255), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('appointment_made_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=50), nullable=True),
    sa.Column('house_price', sa.String(length=255), nullable=True),
    sa.Column('house_location', sa.String(length=100), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('appointments', sa.Integer(), nullable=True),
    sa.Column('posts_added', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointments'], ['appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['posts_added'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['role'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('posts')
    op.drop_table('roles')
    op.drop_table('categories')
    op.drop_table('appointments')
    # ### end Alembic commands ###
