"""adds more tables and relationships

Revision ID: 60146f0a843d
Revises: 3ff6d64b32ff
Create Date: 2021-06-24 15:48:35.726183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60146f0a843d'
down_revision = '3ff6d64b32ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_role', sa.Integer(), nullable=True))
    op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['user_role'], ['role_id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_fkey', 'users', 'roles', ['role'], ['role_id'])
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
